# fly.toml app configuration file generated for uma-ladder on 2026-05-05T19:48:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uma-ladder'
primary_region = 'fra'

[build]

[env]
  FLASK_APP = 'uma_ladder'
  FLASK_CONFIG = 'production'
  PORT = '8080'
  TAILWIND_BUILT = '1'

[[mounts]]
  source = 'uma_ladder_uploads_v3'
  destination = '/app/instance'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
