# fly.toml app configuration file generated for uma-ladder on 2025-07-12T14:41:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uma-ladder'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "uma_data"
  destination = "/data"

[checks]
  [checks.alive]
    type = "http"
    path = "/"
    interval = "15s"
    timeout = "5s"
    grace_period = "60s"
