"""create official_races, registrations, results

Revision ID: 023957103ed4
Revises: 4f86f2a573bc
Create Date: 2026-05-04 18:46:22.166301

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '023957103ed4'
down_revision = '4f86f2a573bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('organizer_user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('room_code', sa.String(length=32), nullable=True),
    sa.Column('room_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preset_id'], ['race_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('official_races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_races_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_races_status'), ['status'], unique=False)

    op.create_table('official_race_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_race_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['official_race_id'], ['official_races.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_race_id', 'user_id', name='uq_official_race_registrations_race_user')
    )
    with op.batch_alter_table('official_race_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_race_registrations_official_race_id'), ['official_race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_race_registrations_user_id'), ['user_id'], unique=False)

    op.create_table('official_race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_race_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uma_character_id', sa.Integer(), nullable=True),
    sa.Column('uma_name', sa.String(length=128), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('guts', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['official_race_id'], ['official_races.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uma_character_id'], ['uma_characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_race_id', 'placement', name='uq_official_race_results_race_placement'),
    sa.UniqueConstraint('official_race_id', 'user_id', name='uq_official_race_results_race_user')
    )
    with op.batch_alter_table('official_race_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_race_results_official_race_id'), ['official_race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_race_results_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_race_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_race_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_official_race_results_official_race_id'))

    op.drop_table('official_race_results')
    with op.batch_alter_table('official_race_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_race_registrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_official_race_registrations_official_race_id'))

    op.drop_table('official_race_registrations')
    with op.batch_alter_table('official_races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_races_status'))
        batch_op.drop_index(batch_op.f('ix_official_races_season_id'))

    op.drop_table('official_races')
    # ### end Alembic commands ###
