"""create user_profiles and uma_characters

Revision ID: 2d5f28a06321
Revises: c75396145e85
Create Date: 2026-05-04 18:31:56.695623

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2d5f28a06321'
down_revision = 'c75396145e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uma_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_jp', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('profile_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uma_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uma_characters_slug'), ['slug'], unique=True)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('friend_code', sa.String(length=32), nullable=True),
    sa.Column('discord_handle', sa.String(length=64), nullable=True),
    sa.Column('oshi_character_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oshi_character_id'], ['uma_characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_oshi_character_id'), ['oshi_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_oshi_character_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('uma_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uma_characters_slug'))

    op.drop_table('uma_characters')
    # ### end Alembic commands ###
