"""PR-X2: api_tokens for the race extractor

Revision ID: 3f61c07a9d24
Revises: 2524b5d899e5
Create Date: 2026-08-04

Hand-written, not autogenerated: `flask db migrate` wants to rewrite
foreign keys on official_races / draft_matches / draft_match_bans /
draft_race_results (pre-existing model-vs-schema drift). Those
batch_alter_table calls rebuild the table in SQLite and drop rows
hanging off CASCADE foreign keys — the PR-J10 production wipe. Only
the new table is created here.
"""
import sqlalchemy as sa
from alembic import op

revision = "3f61c07a9d24"
down_revision = "2524b5d899e5"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_api_tokens_user_id", "api_tokens", ["user_id"], unique=False
    )
    op.create_index(
        "ix_api_tokens_token_digest", "api_tokens", ["token_digest"], unique=True
    )


def downgrade():
    op.drop_index("ix_api_tokens_token_digest", table_name="api_tokens")
    op.drop_index("ix_api_tokens_user_id", table_name="api_tokens")
    op.drop_table("api_tokens")
