"""create seasons and race_presets

Revision ID: 4f86f2a573bc
Revises: 2d5f28a06321
Create Date: 2026-05-04 18:40:18.663285

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4f86f2a573bc'
down_revision = '2d5f28a06321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_source_url', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('surface', sa.String(length=8), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('distance_category', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('course_variant', sa.String(length=32), nullable=True),
    sa.Column('max_runners', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'surface', 'distance_meters', 'direction', 'course_variant', name='uq_race_presets_natural_key')
    )
    with op.batch_alter_table('race_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_presets_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_presets_distance_category'), ['distance_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_presets_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_presets_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_presets_surface'), ['surface'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_presets_venue'), ['venue'], unique=False)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('official_enabled', sa.Boolean(), nullable=False),
    sa.Column('draft_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    with op.batch_alter_table('race_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_presets_venue'))
        batch_op.drop_index(batch_op.f('ix_race_presets_surface'))
        batch_op.drop_index(batch_op.f('ix_race_presets_source'))
        batch_op.drop_index(batch_op.f('ix_race_presets_grade'))
        batch_op.drop_index(batch_op.f('ix_race_presets_distance_category'))
        batch_op.drop_index(batch_op.f('ix_race_presets_direction'))

    op.drop_table('race_presets')
    # ### end Alembic commands ###
