"""create draft_matches and related tables

Revision ID: 6decd77fd2f3
Revises: 023957103ed4
Create Date: 2026-05-04 18:55:49.366602

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6decd77fd2f3'
down_revision = '023957103ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('opponent_user_id', sa.Integer(), nullable=True),
    sa.Column('join_code', sa.String(length=16), nullable=False),
    sa.Column('umas_per_player', sa.Integer(), nullable=False),
    sa.Column('preset_pool', sa.String(length=16), nullable=False),
    sa.Column('selected_preset_id', sa.Integer(), nullable=True),
    sa.Column('room_code', sa.String(length=32), nullable=True),
    sa.Column('room_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('loser_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loser_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opponent_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_preset_id'], ['race_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_matches_host_user_id'), ['host_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_matches_join_code'), ['join_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_draft_matches_opponent_user_id'), ['opponent_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_matches_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_matches_status'), ['status'], unique=False)

    op.create_table('draft_elo_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_match_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opponent_user_id', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Integer(), nullable=False),
    sa.Column('rating_after', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_match_id'], ['draft_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_elo_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_elo_changes_draft_match_id'), ['draft_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_elo_changes_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_elo_changes_user_id'), ['user_id'], unique=False)

    op.create_table('draft_match_uma_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uma_character_id', sa.Integer(), nullable=True),
    sa.Column('custom_uma_name', sa.String(length=128), nullable=True),
    sa.Column('build_nickname', sa.String(length=128), nullable=True),
    sa.Column('screenshot_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_match_id'], ['draft_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uma_character_id'], ['uma_characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_match_uma_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_match_uma_entries_draft_match_id'), ['draft_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_match_uma_entries_user_id'), ['user_id'], unique=False)

    op.create_table('draft_match_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ban_type', sa.String(length=32), nullable=False),
    sa.Column('banned_uma_entry_id', sa.Integer(), nullable=True),
    sa.Column('condition_key', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['banned_uma_entry_id'], ['draft_match_uma_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_match_id'], ['draft_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_match_bans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_match_bans_draft_match_id'), ['draft_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_match_bans_user_id'), ['user_id'], unique=False)

    op.create_table('draft_race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uma_entry_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('guts', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_match_id'], ['draft_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uma_entry_id'], ['draft_match_uma_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_race_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_race_results_draft_match_id'), ['draft_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_race_results_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_race_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_race_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_draft_race_results_draft_match_id'))

    op.drop_table('draft_race_results')
    with op.batch_alter_table('draft_match_bans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_match_bans_user_id'))
        batch_op.drop_index(batch_op.f('ix_draft_match_bans_draft_match_id'))

    op.drop_table('draft_match_bans')
    with op.batch_alter_table('draft_match_uma_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_match_uma_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_draft_match_uma_entries_draft_match_id'))

    op.drop_table('draft_match_uma_entries')
    with op.batch_alter_table('draft_elo_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_elo_changes_user_id'))
        batch_op.drop_index(batch_op.f('ix_draft_elo_changes_season_id'))
        batch_op.drop_index(batch_op.f('ix_draft_elo_changes_draft_match_id'))

    op.drop_table('draft_elo_changes')
    with op.batch_alter_table('draft_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_matches_status'))
        batch_op.drop_index(batch_op.f('ix_draft_matches_season_id'))
        batch_op.drop_index(batch_op.f('ix_draft_matches_opponent_user_id'))
        batch_op.drop_index(batch_op.f('ix_draft_matches_join_code'))
        batch_op.drop_index(batch_op.f('ix_draft_matches_host_user_id'))

    op.drop_table('draft_matches')
    # ### end Alembic commands ###
